In [3]:
import pandas as pd
import numpy as np

In [4]:
import pandas_datareader as pdr
key = "4412be54f9ecbfe7303a63f224bb63e7d0474e30"

In [5]:
df = pdr.get_data_tiingo('AAPL', api_key=key)
df.to_csv('AAPL.csv')
df=pd.read_csv('AAPL.csv')

In [6]:
df.head()

symbol                       date   close    high       low    open  \
0   AAPL  2015-06-18 00:00:00+00:00  127.88  128.31  127.2200  127.23   
1   AAPL  2015-06-19 00:00:00+00:00  126.60  127.82  126.4000  127.71   
2   AAPL  2015-06-22 00:00:00+00:00  127.61  128.06  127.0800  127.49   
3   AAPL  2015-06-23 00:00:00+00:00  127.03  127.61  126.8792  127.48   
4   AAPL  2015-06-24 00:00:00+00:00  128.11  129.80  127.1200  127.21   

     volume    adjClose     adjHigh      adjLow     adjOpen  adjVolume  \
0  35407220  117.844413  118.240668  117.236207  117.245422   35407220   
1  54716887  116.664863  117.789121  116.480558  117.687754   54716887   
2  34039345  117.595601  118.010287  117.107194  117.485018   34039345   
3  30268863  117.061118  117.595601  116.922152  117.475803   30268863   
4  55280855  118.056363  119.613737  117.144055  117.226992   55280855   

   divCash  splitFactor  
0      0.0          1.0  
1      0.0          1.0  
2      0.0          1.0  
3      0.0          1.0  
4      0.0          1.0

In [7]:
df.tail()

symbol                       date   close    high       low    open  \
1252   AAPL  2020-06-09 00:00:00+00:00  343.99  345.61  332.0100  332.14   
1253   AAPL  2020-06-10 00:00:00+00:00  352.84  354.77  346.0900  347.90   
1254   AAPL  2020-06-11 00:00:00+00:00  335.90  351.06  335.4800  349.31   
1255   AAPL  2020-06-12 00:00:00+00:00  338.80  347.80  334.2233  344.72   
1256   AAPL  2020-06-15 00:00:00+00:00  342.99  345.68  332.5800  333.25   

        volume  adjClose  adjHigh    adjLow  adjOpen  adjVolume  divCash  \
1252  36928091    343.99   345.61  332.0100   332.14   36928091      0.0   
1253  41662938    352.84   354.77  346.0900   347.90   41662938      0.0   
1254  50415613    335.90   351.06  335.4800   349.31   50415613      0.0   
1255  50036513    338.80   347.80  334.2233   344.72   50036513      0.0   
1256  34702230    342.99   345.68  332.5800   333.25   34702230      0.0   

      splitFactor  
1252          1.0  
1253          1.0  
1254          1.0  
1255          1.0  
1256          1.0

In [8]:
df.head(1)

symbol                       date   close    high     low    open    volume  \
0   AAPL  2015-06-18 00:00:00+00:00  127.88  128.31  127.22  127.23  35407220   

     adjClose     adjHigh      adjLow     adjOpen  adjVolume  divCash  \
0  117.844413  118.240668  117.236207  117.245422   35407220      0.0   

   splitFactor  
0          1.0

In [9]:
df.tail(100)

symbol                       date   close    high       low    open  \
1157   AAPL  2020-01-23 00:00:00+00:00  319.23  319.56  315.6500  317.92   
1158   AAPL  2020-01-24 00:00:00+00:00  318.31  323.33  317.5188  320.25   
1159   AAPL  2020-01-27 00:00:00+00:00  308.95  311.77  304.8800  310.06   
1160   AAPL  2020-01-28 00:00:00+00:00  317.69  318.40  312.1900  312.60   
1161   AAPL  2020-01-29 00:00:00+00:00  324.34  327.85  321.3800  324.45   
...     ...                        ...     ...     ...       ...     ...   
1252   AAPL  2020-06-09 00:00:00+00:00  343.99  345.61  332.0100  332.14   
1253   AAPL  2020-06-10 00:00:00+00:00  352.84  354.77  346.0900  347.90   
1254   AAPL  2020-06-11 00:00:00+00:00  335.90  351.06  335.4800  349.31   
1255   AAPL  2020-06-12 00:00:00+00:00  338.80  347.80  334.2233  344.72   
1256   AAPL  2020-06-15 00:00:00+00:00  342.99  345.68  332.5800  333.25   

        volume    adjClose     adjHigh      adjLow     adjOpen  adjVolume  \
1157  26117993  317.623954  317.952294  314.061965  316.320545   26117993   
1158  36634380  316.708583  321.703327  315.921363  318.638822   36634380   
1159  40485005  307.395673  310.201485  303.346149  308.500088   40485005   
1160  40558486  316.091702  316.798130  310.619372  311.027310   40558486   
1161  54149928  322.708246  326.200587  319.763137  322.817692   54149928   
...        ...         ...         ...         ...         ...        ...   
1252  36928091  343.990000  345.610000  332.010000  332.140000   36928091   
1253  41662938  352.840000  354.770000  346.090000  347.900000   41662938   
1254  50415613  335.900000  351.060000  335.480000  349.310000   50415613   
1255  50036513  338.800000  347.800000  334.223300  344.720000   50036513   
1256  34702230  342.990000  345.680000  332.580000  333.250000   34702230   

      divCash  splitFactor  
1157      0.0          1.0  
1158      0.0          1.0  
1159      0.0          1.0  
1160      0.0          1.0  
1161      0.0          1.0  
...       ...          ...  
1252      0.0          1.0  
1253      0.0          1.0  
1254      0.0          1.0  
1255      0.0          1.0  
1256      0.0          1.0  

[100 rows x 14 columns]

In [10]:
df1=df.reset_index()['close']

In [11]:
df1

0       127.88
1       126.60
2       127.61
3       127.03
4       128.11
         ...  
1252    343.99
1253    352.84
1254    335.90
1255    338.80
1256    342.99
Name: close, Length: 1257, dtype: float64

In [12]:
import matplotlib.pyplot as plt
plt.plot(df1)

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
df1=scaler.fit_transform(np.array(df1).reshape(-1,1))
print(df1)

[[0.14300952]
 [0.13813333]
 [0.14198095]
 ...
 [0.93546667]
 [0.94651429]
 [0.96247619]]


In [14]:
training_size=int(len(df1)*0.65)
test_size=len(df1)-training_size
train_data,test_data=df1[0:training_size,:],df1[training_size:len(df1),:1]

In [15]:
training_size

817

In [16]:
test_size

440

In [17]:
train_data

array([[0.14300952],
       [0.13813333],
       [0.14198095],
       [0.13977143],
       [0.14388571],
       [0.1415619 ],
       [0.13870476],
       [0.13024762],
       [0.13365714],
       [0.13813333],
       [0.13752381],
       [0.13584762],
       [0.13466667],
       [0.12278095],
       [0.11325714],
       [0.12548571],
       [0.13455238],
       [0.1343619 ],
       [0.13897143],
       [0.14540952],
       [0.1496381 ],
       [0.15897143],
       [0.15394286],
       [0.13287619],
       [0.13264762],
       [0.13013333],
       [0.12354286],
       [0.12586667],
       [0.12438095],
       [0.12201905],
       [0.11794286],
       [0.10704762],
       [0.09257143],
       [0.09546667],
       [0.0944381 ],
       [0.09592381],
       [0.11192381],
       [0.08819048],
       [0.09485714],
       [0.09451429],
       [0.0976    ],
       [0.10217143],
       [0.09965714],
       [0.09398095],
       [0.08499048],
       [0.05874286],
       [0.04868571],
       [0.051

In [18]:
import numpy
# convert array of values into a dataset matrix
def create_dataset(dataset, time_step=1):
	dataX, dataY = [], []
	for i in range(len(dataset)-time_step-1):
		a = dataset[i:(i+time_step), 0] 
		dataX.append(a)
		dataY.append(dataset[i + time_step, 0])
	return numpy.array(dataX), numpy.array(dataY)

In [19]:
time_step = 100
X_train,y_train = create_dataset(train_data,time_step)
X_test,y_test = create_dataset(test_data,time_step)

In [20]:
X_train

array([[0.14300952, 0.13813333, 0.14198095, ..., 0.12060952, 0.11649524,
        0.11702857],
       [0.13813333, 0.14198095, 0.13977143, ..., 0.11649524, 0.11702857,
        0.1151619 ],
       [0.14198095, 0.13977143, 0.14388571, ..., 0.11702857, 0.1151619 ,
        0.10068571],
       ...,
       [0.33333333, 0.31413333, 0.2871619 , ..., 0.52011429, 0.50575238,
        0.49889524],
       [0.31413333, 0.2871619 , 0.28533333, ..., 0.50575238, 0.49889524,
        0.48758095],
       [0.2871619 , 0.28533333, 0.27657143, ..., 0.49889524, 0.48758095,
        0.50860952]])

In [21]:
print(X_train.shape)

(716, 100)


In [22]:
print(X_test)

[[0.50857143 0.48586667 0.4872381  ... 0.31939048 0.31961905 0.30704762]
 [0.48586667 0.4872381  0.48773333 ... 0.31961905 0.30704762 0.30502857]
 [0.4872381  0.48773333 0.49405714 ... 0.30704762 0.30502857 0.30129524]
 ...
 [0.8567619  0.87005714 0.86182857 ... 0.91870476 0.92617143 0.96628571]
 [0.87005714 0.86182857 0.86613333 ... 0.92617143 0.96628571 1.        ]
 [0.86182857 0.86613333 0.8719619  ... 0.96628571 1.         0.93546667]]


In [23]:
print(X_test.shape)

(339, 100)


In [24]:
print(y_test.shape)

(339,)


In [25]:
print(y_train.shape)

(716,)


In [26]:
#time_step = 101
#X_train,y_train = create_dataset(train_data,time_step)
#X_test,y_test = create_dataset(test_data,time_step)

In [27]:
print(X_test.shape)

(338, 101)
